### ISSUE TITLE
The example handlebars solution refers to an incorrect project name

### ISSUE THREAD

**Issue by tuan1978** [RoelantVos/Data-Warehouse-Automation-Metadata-Schema#1]
The file Examples\DV_Handlebars.sln incorrectly refers to the project called DV_Handlebars\DV_Handlebars.csproj. There's a file called Example_Handlebars.csproj which might be the correct project.

**Comment by RoelantVos** [comment]
Hi - Example_Handlebars.csproj is indeed the correct project. I have removed the old DV_Handlebars solution as this was indeed obsolete. For completeness I have created a new solution file for the Example_Handlebars. However, it is best to just use the ClassLibrary solution 'DataWarehouseAutomation'. This also refers to the Example_Handlebars, so shows all projects in a single solution.

**Comment by tuan1978** [comment]
Yes, I saw that solution later thanks.
