### ISSUE TITLE
What about Meta Data from previously unknown header info

### ISSUE THREAD

**Issue by papyr** [RoelantVos/Data-Warehouse-Automation-Metadata-Schema#3]
in my case, the _source CSV data file_ and header content/types change often -- basically unknown, while parsing or before parsing I need to first Discover the Data Types of the data in the cols.

I just need to load & save the data into a Sql table based on whatever data & DataTypes there are in the CSV file. Can I auto load the CSV data and datatypes into the DB automatically with ETL box. I saw your expando example but was a little lost how to achieve a high level task

For e.g high level algorithm, how would I achieve this in your lib.
```
// Scan first 9 rows to discover the datatypes in the CSV file cols
var etlPrasedFile = Data_WareHOuse.Open/parseCSV(someUnknownData.csv).ScanRows(9)
foreach (var col in etlPrasedFile )
new dataTable.addColumn(etlParsedFile.GetNextHeaderCol)
CreateNewSqlServerTable
LoadDatatoSqlTable??
```

thanks

**Comment by RoelantVos** [comment]
Hi – I know what you mean, in the past I have used C# to read the columns and create a table in a database to be able to stash the CSV somewhere. The library is intended to capture source-to-target mappings more geared towards transformations between one database table and another. 

 

Having said that, you can map this from a file to a table also and store this but in this case the structure must be known.

**Comment by papyr** [comment]
Well, then I can still use it for another use case 👍 

How do I go about mapping one table to another table in a different database. Do you have a sample posted online/wiki

**Comment by RoelantVos** [comment]
Hi there!

 

There are a few samples in the example project, one of which has connectivity information included also. 

 

It’s basically an object mapped to another object, with each object having a connection you can specify.

 

Kind regards,

Roelant

**Comment by RoelantVos** [comment]
From: Roelant Vos <roelant@ravos.nl> 
Sent: Sunday, 28 February 2021 18:38
To: 'Fodi Dervidis' <fodi@outlook.com>; 'Sam Spencer' <SSpencer@allianz-assistance.com.au>; 'aaronblakeney@yahoo.com.au' <aaronblakeney@yahoo.com.au>; 'Allan Duckwitz' <ADuckwitz@allianz-assistance.com.au>; 'Adam Raffa' <ARaffa@allianz-assistance.com.au>; 'devereaux64@gmail.com' <devereaux64@gmail.com>; 'hellobenchen@gmail.com' <hellobenchen@gmail.com>; 'lmweber@hotmail.com' <lmweber@hotmail.com>; 'luciano.bastian@gmail.com' <luciano.bastian@gmail.com>; 'mehdireleh@yahoo.com' <mehdireleh@yahoo.com>; 'mwaters1973@gmail.com' <mwaters1973@gmail.com>; 'Ashley Peet' <APeet@allianz-assistance.com.au>; 'ej@live.nl' <ej@live.nl>
Subject: RE: [EXT] LAN party - March 12th

 

Thanks Fodi, looks like we’re good with the tables then!

 

Any ideas on games and/or setup?
